button_to_calculate.param.watch(get_ttmap_from_inputs, parameter_names='clicks')
query_dropdown.param.watch(query_columns, parameter_names='value')
query_box.param.watch(query_columns, parameter_names='value')
query_box_deviated_genes.param.watch(query_clusters, parameter_names='value')
query_genes.param.watch(query_clusters, parameter_names='value')
